/*
 * BMP280_ForUser_Registers.h
 *
 * Created: 16.01.2022 18:58:09
 *  Author: Михаил
 */ 


#ifndef BMP280_FORUSER_REGISTERS_H_
#define BMP280_FORUSER_REGISTERS_H_
//пользовательские дефайны
#define SLEEP_MODE 0
#define FORCED_MODE 1
#define NORMAL_MODE 2
#define FREQUENCY_MEASUREMENT_500hS 0
#define FREQUENCY_MEASUREMENT_62500hS 1
#define FREQUENCY_MEASUREMENT_125mS 2
#define FREQUENCY_MEASUREMENT_250mS 3
#define FREQUENCY_MEASUREMENT_500mS 4
#define FREQUENCY_MEASUREMENT_1S 5
#define FREQUENCY_MEASUREMENT_2S 6
#define FREQUENCY_MEASUREMENT_4S 7
#define PRESSURE_OVERSAMPLING_SKIPPED 0
#define PRESSURE_OVERSAMPLING_1 1
#define PRESSURE_OVERSAMPLING_2 2
#define PRESSURE_OVERSAMPLING_4 3
#define PRESSURE_OVERSAMPLING_8 4
#define PRESSURE_OVERSAMPLING_16 5
#define TEMPERATURE_OVERSAMPLING_SKIPPED 0
#define TEMPERATURE_OVERSAMPLING_1 1
#define TEMPERATURE_OVERSAMPLING_2 2
#define TEMPERATURE_OVERSAMPLING_4 3
#define TEMPERATURE_OVERSAMPLING_8 4
#define TEMPERATURE_OVERSAMPLING_16 5
#define FILTER_COEFFICIENT_OFF 0
#define FILTER_COEFFICIENT_2 1
#define FILTER_COEFFICIENT_4 2
#define FILTER_COEFFICIENT_8 3
#define FILTER_COEFFICIENT_16 4
#define Compensation_Pressure 0
#endif /* BMP280_FORUSER_REGISTERS_H_ */